# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate signed APK

on:
  pull_request:
    branches: [develop]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Add google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "gwent-keystore"
          fileDir: "./app/"
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Add signing.properties
        env:
          KEYPASS: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          echo "signing.password=$KEYPASS" > ./app/signing.properties 
          echo "signing.alias=gwent" >> ./app/signing.properties 
          echo "signing.keypassword=$KEYPASS" >> ./app/signing.properties
      - name: Bump Build Version
        run: ./gradlew bumpBuildNumber
      - name: Clean
        run: ./gradlew clean
      - name: Build debug
        run: ./gradlew assembleRelease

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version code

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: gwent-app
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
